# Generated by Django 4.2.16 on 2025-01-27 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_admission_parent_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='nemis',
        ),
        migrations.AddField(
            model_name='admission',
            name='learner_upi',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
